meta:
  environment: sensu-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: sensu1

  - name: rabbitmq_server
    networks:
      - name: sensu1
        static_ips: (( static_ips(0,1,2,3) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: sensu1
  type: manual
  subnets:
  - range: 10.244.117.0/24
    name: sensu1
    gateway: 10.244.117.1
    static:
      - 10.244.117.2 - 10.244.117.60
